TRUNCATE TABLE employer CASCADE;
TRUNCATE TABLE vacancy CASCADE;
TRUNCATE TABLE area CASCADE;
TRUNCATE TABLE employer_counter CASCADE;
TRUNCATE TABLE vacancy_counter CASCADE;
TRUNCATE TABLE employer_comment CASCADE;
TRUNCATE TABLE vacancy_comment CASCADE;